### ISSUE TITLE
A problem of Print Pages

### ISSUE THREAD

**Issue by zby0327** [Liu233w/acm-statistics#1129]
If I click on the Print Page and save it as a PDF on the website, the page will be printed twice. Could you have a check and modify that?

**Comment by Liu233w** [comment]
I just checked it in Firefox and Chrome and did not find the problem. Could you please tell me your browser and version?

**Comment by Liu233w** [comment]
hmmmm, I found that if the table is too long, it is printed twice...

**Comment by zby0327** [comment]
Thnaks!
