### ISSUE TITLE
Add PTA to your crawler

### ISSUE THREAD

**Issue by zby0327** [Liu233w/acm-statistics#1137]
There are many problems in pintia.cn. but it's a little hard to find solved lists...... just like leetcode.
So could you have a try and add it to the crawler list?

**Comment by Liu233w** [comment]
I do plan to re-support [ZOJ](https://zoj.pintia.cn/problem-sets/91827364500/submissions), but it needs a crawler with backend, which is in [branch ohunt](https://github.com/Liu233w/acm-statistics/tree/feat-ohunt/ohunt). Unfortunately I'm too busy to work on this feature recently. Fell free to contribute!
