### ISSUE TITLE
Total number of accepted problems disappeared

### ISSUE THREAD

**Issue by zby0327** [Liu233w/acm-statistics#1172]
When I use the website https://new.npuacm.info/statistics , the box on the upper right corner showing accepted numbers will appear for a while and disappear at last so I cannot save the detailed information. 
Why does that happen and how can I avoid it? Thanks for your reply.

**Comment by Liu233w** [comment]
It disappears when that last crawler with results resets.

A crawler resets when
- You re-query the crawler (click re-query button on crawler panel or QUERY button near 'set all usernames' input)
- The username in the crawler is changed (set the username or all usernames, click the ❌button near crawler usernames, or click the RESET button)

**Comment by zby0327** [comment]
However, when I do not click on anything, the box still disappears... How can I avoid that?

**Comment by Liu233w** [comment]
Could you please offer your browser version? I cannot reproduce it on my computer \_(:3」∠)_

**Comment by zby0327** [comment]
Both the latest version of Edge (83.0.478.58) and Chrome (83.0.4103.116) with the username **zby0327** and **166580923** in nowcoder.

**Comment by zby0327** [comment]
![image](https://user-images.githubusercontent.com/43291744/86430087-e8797380-bd23-11ea-884d-006384ad29b7.png)
Now the box appears, but I found the page cannot be opened...

**Comment by zby0327** [comment]
[AC Statistics - NWPU-ACM 查询系统 - Google Chrome 2020-07-03 11-58-27.zip](https://github.com/Liu233w/acm-statistics/files/4867669/AC.Statistics.-.NWPU-ACM.-.Google.Chrome.2020-07-03.11-58-27.zip)
It's a video of this bug.

**Comment by Liu233w** [comment]
hmmmm, it is the issue of UOJ crawler.

It returns wrong output when the user has no submissions.

You can temporary clear your user name in uoj while I fix it.
