### ISSUE TITLE
vjudge获取数据接口

### ISSUE THREAD

**Issue by Mr-CHANX** [Liu233w/acm-statistics#1197]
注释说是vj的一个api接口需要登录才能调用

我现在本地部署后（已改vj的用户名和密码）发现vjudge登录失败。不是很清楚是什么原因

**我从VJ的个人信息页面得到一个接口，该接口能直接获取到某用户的详细做题信息**

是不是改用该接口就可以不用进行登录这么一个前置操作？

```
//此处为获取mchanx用户的详细做题信息
URL：https://vjudge.net/user/solveDetail/mchanx
Method：GET
```

**Comment by Liu233w** [comment]
我使用那个api是沿用了旧版查询系统的设计，既然可以从这个接口获取数据的话，我可以在下个版本改成不需要登录的代码。

另外，你可以查看本地的日志来找原因。在有`docker-compose.yml`的目录下使用`docker-compose logs crawler-api-service` 可以查看爬虫后端的日志。

**Comment by Liu233w** [comment]
还有就是目前自己部署的话并不能加快浏览器端的查询速度，因为目前浏览器端的查询都会统一走 cors-proxy (url: https://cors-anywhere.herokuapp.com/ 在 #1198 之后是 https://acm-statistics-cors.herokuapp.com/)

**Comment by Liu233w** [comment]
emmmmm突然发现如果用这个api的话就没法获取vjudge在每个OJ的提交数了。。。

**Comment by Mr-CHANX** [comment]
> emmmmm突然发现如果用这个api的话就没法获取vjudge在每个OJ的提交数了。。。

啊！这也是个问题。

**Comment by Liu233w** [comment]
大佬如果没有问题的话我就先关了啊23333
