### ISSUE TITLE
About DMOJ

### ISSUE THREAD

**Issue by zby0327** [Liu233w/acm-statistics#1341]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zby0327** [comment]
Could you provide a crawler for the oj which uses framework of DMOJ ?

**Comment by Liu233w** [comment]
AC: https://dmoj.ca/submissions/user/zhouzixiang2004/?status=AC
Submissions: https://dmoj.ca/submissions/user/zhouzixiang2004/
`$('#total-submission-count').text()`

**Comment by Liu233w** [comment]
Get AC problem using API: https://dmoj.ca/api/v2/user/Xyene
