### ISSUE TITLE
洛谷是爬不了了吗

### ISSUE THREAD

**Issue by bluebear4** [Liu233w/acm-statistics#1358]
洛谷是爬不了了吗

**Comment by Liu233w** [comment]
惊了，洛谷怎么整天出事的_(:3」∠)_

**Comment by Liu233w** [comment]
粗略看了一下，原先的通过用户名来找ID的方式失效了。如果找不到替代的方法的话以后就只能用ID来查询了。

**Comment by Liu233w** [comment]
其实只是api的url改了一下，等上面的那个commit合并就好了
