### ISSUE TITLE
Uoj 爬取时出现问题

### ISSUE THREAD

**Issue by BackSlashDelta** [Liu233w/acm-statistics#1469]
当我想查看我 UOJ 的状态时，它出现了这个东西：

![image](https://user-images.githubusercontent.com/64258212/99137239-651e4600-2664-11eb-836e-a5a9daaaf441.png)

我确认我已经注册了 UOJ 的帐户，但还是无法查看。是我操作有误吗？

**Comment by Liu233w** [comment]
是 bug \_(:3」∠)_

我已经修复了，过一段时间就会部署到服务器上。

@all-contributors please add @BackSlashDelta for bug
