### ISSUE TITLE
leetcode貌似爬取出错？

### ISSUE THREAD

**Issue by bodhisatan** [Liu233w/acm-statistics#239]
爬取本人的账号时，leetcode部分出现了诡异的1000+/70000+

**Comment by Liu233w** [comment]
hi，可以提供一下你的帐号吗？我用我的帐号试过是可以的

**Comment by bodhisatan** [comment]
账号可以qq私聊吗（我用了别人的账号也是可以的，但我自己的就是不对qwq

**Comment by Liu233w** [comment]
要不您发到我邮箱里吧_(:3」∠)_

在 2018年10月8日，下午4:07，Bodhisatan_Yao <notifications@github.com<mailto:notifications@github.com>> 写道：


账号可以qq私聊吗（我用了别人的账号也是可以的，但我自己的就是不对qwq

**Comment by Liu233w** [comment]
fixed in #240

**Comment by Liu233w** [comment]
@all-contributors add @bodhisatan for bug
