### ISSUE TITLE
洛谷的爬虫出了问题

### ISSUE THREAD

**Issue by CCH21** [Liu233w/acm-statistics#2442]
查询的时候，洛谷的爬虫会出现“Forbidden”字样，并且无法返回数据。
![image](https://user-images.githubusercontent.com/57098771/152735863-7adc1152-dd87-4997-9270-f54f4d387203.png)

**Comment by Liu233w** [comment]
惊了，居然又出问题_(:3」∠)_

**Comment by Liu233w** [comment]
@CCH21 看起来洛谷加了一个区域限制，某些ip已经没法访问这个网站了。但是ojhunt的服务器端爬虫API还能访问。我现在可以先把它调成直接用服务器端爬虫来获取数据。但如果以后我的服务器进了黑名单的话就没办法了_(:3」∠)_
