### ISSUE TITLE
洛谷爬取异常

### ISSUE THREAD

**Issue by Find-NICK** [Liu233w/acm-statistics#2971]
如题

![image](https://github.com/Liu233w/acm-statistics/assets/116571277/cdf15c9e-a428-4736-a31e-359ba988eacb)

**Comment by Liu233w** [comment]
Hi,  我刚刚检查了一下，貌似是因为洛谷加上了cloudflare的防ddos机制，导致爬虫没办法直接访问了。这个只能等到他们把这个关上才能继续用了。
