### ISSUE TITLE
对于爬虫的一点建议

### ISSUE THREAD

**Issue by Geekxiong** [Liu233w/acm-statistics#462]
在使用的时候发现有些oj会出现404，然后发现作者您用的是js做请求然后 https://cors-anywhere.herokuapp.com 解决跨域。其实个人觉得可以用nginx做代理来解决跨域问题。

**Comment by Liu233w** [comment]
emmmmm这里我用前端爬虫的目的就是为了减轻服务器的压力，如果这里用自己的服务器来转发跨域流量的话，估计对服务器造成的压力比后端爬虫还要大。

另外404的问题我在自己做测试的时候没有遇到过，请问具体是哪个oj会这样呢？

**Comment by Liu233w** [comment]
现在已知有些oj在晚上的时候会暂停访问，那时候爬虫肯定是失效的。另外，这边确实有一个优化这个功能的计划 (#398 )

**Comment by Geekxiong** [comment]
哈， HDU会这样，其他的有些也时好时坏。 担心服务器压力的话，其实可以在nginx上面设置缓存，几分钟的缓存什么的可以。还有就是想问   https://cors-anywhere.herokuapp.com 会限制你的请求次数或者 qps么？昨天用的时候提示请求太多。。

**Comment by Liu233w** [comment]
确实是会限制次数，不过这个限制的是请求端（浏览器）的ip。考虑到每个用户查询的次数不会很多，我感觉这个还可以接受_(:3」∠)_

**Comment by Geekxiong** [comment]
额， 可能有些学校的出口ip就那么一两个吧，所以我昨天没有查成功，

**Comment by Liu233w** [comment]
emmmmm我确实没考虑过这种情况，看来 #398 得赶紧干了

**Comment by Geekxiong** [comment]
ok 加油

**Comment by Liu233w** [comment]
@all-contributors add @Geekxiong for ideas

**Comment by Liu233w** [comment]
@all-contributors add @Geekxiong for ideas

**Comment by Liu233w** [comment]
@all-contributors add @Geekxiong for ideas
