### ISSUE TITLE
添加一些其余的常用OJ

### ISSUE THREAD

**Issue by Halorv** [Liu233w/acm-statistics#546]
比如LOJ，洛谷

**Comment by Liu233w** [comment]
hi, 我刚刚看了一下这两个 OJ 的用户主页网址都是用的 id 的形式，比如 `https://loj.ac/user/1` 和 `https://www.luogu.org/space/show?uid=1` ，如果想让用户方便找到自己的用户名对应的题目的话，需要某种方法把用户名转换成 id。

LOJ 的话可以用 `https://loj.ac/find_user?nickname=wwwlsmcom` 这样的方法来找ID，不过我暂时还没有找到洛谷里对应的方法。

**Comment by Liu233w** [comment]
LOJ 爬虫逻辑：
使用 `https://loj.ac/find_user?nickname={USERNAME}` 来访问指定的用户名的主页
- 用户不存在： 页面含有 `无此用户`
- 用户存在：跳转到 `https://loj.ac/user/{ID}`

获取数据：
- AC：直接从页面获取
- 提交数：将页面源码中的指定数值相加 
![图片](https://user-images.githubusercontent.com/16333687/57571256-33f50200-743e-11e9-9a9c-9dd1f031ccdd.png)

**Comment by Liu233w** [comment]
洛谷爬虫逻辑：
【暂时不知道怎么获取用户名对应的ID】

获取数据：
- AC：直接获取
- 提交数： 直接获取；在超过1000之后会被简化
![图片](https://user-images.githubusercontent.com/16333687/57571469-59373f80-7441-11e9-9194-0d94ef50c7fb.png)
（获取更精确的数据？）

**Comment by Liu233w** [comment]
close by #581

**Comment by Liu233w** [comment]
@all-contributors add @Halorv  for ideas
