### ISSUE TITLE
征集部分oj的测试账号

### ISSUE THREAD

**Issue by Liu233w** [Liu233w/acm-statistics#7]
我最近正在把 `npuacm.info` 上的爬虫移植到本网站上，需要一些oj的账号来进行测试。如果您愿意提供自己的账号，请直接在下方回复。

注意：
- 只需要用户名，不需要密码
- 测试账号会被写进测试用例中，其他所有浏览本网站源代码的用户都能看到此用户名

需要测试的网站：
- [x] FZU `http://acm.fzu.edu.cn/user.php?uname=`
- [x] Timus OJ `http://acm.timus.ru/search.aspx?Str=`
- [x] SPOJ `http://www.spoj.com/users/`
- [x] SGU `http://acm.sgu.ru/find.php?find_id=`

谢谢大家。

**Comment by Liu233w** [comment]
突然想到我可以用 `vjudgeX` 系列的帐号来测试

**Comment by kidozh** [comment]
2013300262

**Comment by Liu233w** [comment]
@kidozh 谢大佬，你的帐号我已经用上了_(:3」∠)_

**Comment by Liu233w** [comment]
除了 #9 里的OJ以外已经全部完成了
