### ISSUE TITLE
Luogu的功能好像挂了？

### ISSUE THREAD

**Issue by fzu-h4cky** [Liu233w/acm-statistics#721]

**Comment by fzu-h4cky** [comment]
{"error":true,"message":"Cannot read property 'uid' of undefined"}

**Comment by Liu233w** [comment]
emmmm话说Luogu是不是换网址了。为啥我这里没法访问。
![图片](https://user-images.githubusercontent.com/16333687/67176696-bc200000-f3fd-11e9-9270-3e350fd88d29.png)

**Comment by fzu-h4cky** [comment]
网址没换
福建联通 上海联通 北京都可以 你试一下能不能忽略建立安全连接

**Comment by fzu-h4cky** [comment]
这个 感觉是被劫持了

**Comment by Liu233w** [comment]
根据 #735 的说法，好像洛谷的地址现在必须加上 www 前缀了。我改一下代码看看。

**Comment by Liu233w** [comment]
看起来问题是 `https://www.luogu.org/space/ajax_getuid?username=CancerGary` 这个 json api 失效了

**Comment by Liu233w** [comment]
@flylai 大佬，你当时是怎么找到洛谷的API的啊_(:3」∠)_

**Comment by flylai** [comment]
> https://www.luogu.org/chat
> https://www.luogu.org/fe/api/user/search?keyword=username

这里有个搜索用户名，但是现在是要登录才能搜索了.....

**Comment by Liu233w** [comment]
emmmmm如果洛谷有用api登录的功能的话，我可以自己注册一个帐号，然后把爬虫放到服务器端。

**Comment by flylai** [comment]
这个似乎没有，而且登录要验证码....
服务器端直接附加cookies爬取似乎可以？只是cookie要定时更新...

**Comment by 2512821228** [comment]
可能是洛谷用户主页这两天改版的过

**Comment by Liu233w** [comment]
@all-contributors add @fzu-h4cky @2512821228 @flylai @cometeme for bug
