### ISSUE TITLE
添加网站 AcWing 

### ISSUE THREAD

**Issue by 2512821228** [Liu233w/acm-statistics#745]
[AcWing](acwing.com) 是一个 2018 年才开的 oj，上面有大量的优质题目，可以考虑联系站长提供个 API

**Comment by CCWUCMCTS** [comment]
希望能加上51Nod~

**Comment by Liu233w** [comment]
> 
> 
> 希望能加上51Nod~

@CCWUCMCTS 我之前倒是研究过，但是没找到这个网站的 提交数/通过数 从哪里看啊

**Comment by CCWUCMCTS** [comment]
> > 希望能加上51Nod~
> 
> @CCWUCMCTS 我之前倒是研究过，但是没找到这个网站的 提交数/通过数 从哪里看啊

好像提交只能自己看，除非全爬提交状态，不过过题数应该可以url直接加上userId搞到QAQ

**Comment by CCWUCMCTS** [comment]
@Liu233w 好像提交只能自己看，除非全爬提交状态，不过过题数应该可以url直接加上userId搞到QAQ

**Comment by Liu233w** [comment]
如果真的是只有自己能看的话，我还得加一个让用户自己输入密码的功能_(:3」∠)_

On 9 May 2020, at 9:36 pm, CCWUCMCTS <notifications@github.com> wrote:

﻿

@Liu233w<https://github.com/Liu233w> 好像提交只能自己看，除非全爬提交状态，不过过题数应该可以url直接加上userId搞到QAQ

**Comment by Liu233w** [comment]
@2512821228 大佬，acwing到现在还没回复我，我估计是凉了_(:3」∠)_

**Comment by 2512821228** [comment]
@Liu233w 是用acwing右下角的站内通讯工具联系的吗？站长id是 **yxc**
如果不行的话加一下站长qq: **117474335**
网站是在正常更新运营的

**Comment by Liu233w** [comment]
@2512821228 确实是用站内通讯工具联系的。大佬也帮忙联系一下呗_(:3」∠)_

**Comment by Liu233w** [comment]
目前仍然没有收到回复，我就先把这个issue关上了
