### ISSUE TITLE
洛谷爬虫数据无法解析

### ISSUE THREAD

**Issue by GavinZhengOI** [Liu233w/acm-statistics#768]

**Comment by Liu233w** [comment]
看起来是服务器端的查询api出问题了，我先排查一下

**Comment by Liu233w** [comment]
@GavinZhengOI 大佬，我在本地和服务器端都测试过，没有问题啊。你可以发一个错误信息的截图吗？

**Comment by GavinZhengOI** [comment]
> @GavinZhengOI 大佬，我在本地和服务器端都测试过，没有问题啊。你可以发一个错误信息的截图吗？

不是大佬QAQ 
我才想起来我洛谷设置了完全隐私保护QAQ
对不起，给您添麻烦了。
