### ISSUE TITLE
在自己的服务器上部署后VJ爬虫一直失败

### ISSUE THREAD

**Issue by Hukeqing** [Liu233w/acm-statistics#787]
按照README文档操作(今天上午重新下载 run.sh 再部署结果相同)出现如下错误
![TIM截图20200101092840](https://user-images.githubusercontent.com/47495915/71637260-5cee2f80-2c79-11ea-8609-2bd0e1ea2c21.png)
后台的输出内容如下
![TIM截图20200101092645](https://user-images.githubusercontent.com/47495915/71637263-67102e00-2c79-11ea-800c-bf8fed76be1a.png)

**Comment by Liu233w** [comment]
部署之后你还需要编辑一下生成的 .env 文件，在里面填上一个vjudge的用户名和密码。vjudge需要这个才能进行查询。

**Comment by Hukeqing** [comment]
感谢帮助，但是它出现了另外一个错误
![error](https://user-images.githubusercontent.com/47495915/71637653-2fa67f00-2c83-11ea-938b-d0ccf88ed938.png)

**Comment by Liu233w** [comment]
emmmmm我先在自己的电脑上测试一下看看

**Comment by Liu233w** [comment]
emmmmm我也没遇到这个问题。要不你把那个 `test001` 换成别的帐号试一下？

感觉这个有可能是网络问题，比如没有加载完爬虫的数据就超时之类的。

**Comment by Hukeqing** [comment]
我测试了约5个账号，结果相同
仔细查看错误信息和js代码后认为应该不是网络问题
错误显示第144行的 `problemArray` 没有 `length`属性
第134行有`const problemArray = res.body.data`可知 `problemArray `来着 `res` 的 `body.data`
这一行并没有出错，加上130行的结果处理也没有发生错误
我尝试了访问第121行的代码对应的API地址
`  const res = await agent
    .get(`https://${hostName}/user/submissions`)
    .query(queryObject)
`
访问地址为[https://vjudge.net/user/submissions?username=test001&pageSize=100](https://vjudge.net/user/submissions?username=test001&pageSize=100)本地可以正常访问，服务器端看上去也没有问题

**Comment by Liu233w** [comment]
emmmmmm这就很神秘了。我在服务器上部署的时候用的就是这个相同的脚本。大佬你可以测试一下在本地单独运行服务端吗？

步骤（需要安装nodejs）：
1. clone 项目
2. 进入crawler文件夹，`npm install`
3. 进入crawler-api-backend文件夹，`npm install`
4. 为了省事起见直接修改 `crawler/config.yml` 文件，最后两个参数是vjudge的用户名和密码
5. 在 crawler-api-backend 文件夹里运行 `npm start`

如果这样也会出现问题的话，大佬可以直接在爬虫那里加个log看看这个对象的内容。

PS. crawler文件夹是通过软链接挂载到crawler-api-backend 文件夹里的，如果运行crawler-api-backend的时候提示说没找到 crawler的话，需要在crawler-api-backend文件夹里运行 `npm run postinstall`

**Comment by Liu233w** [comment]
emmmmm

@Hukeqing 大佬，这个问题解决了吗？如果解决了我就把问题关了啊。

**Comment by Hukeqing** [comment]
抱歉，最近一直没有用到这个，然后就一直鸽了……

**Comment by Hukeqing** [comment]
大佬抱歉，我又来找你了
我今天做了你上面说的测试，文件是今天刚刚下载的，git的版本是[adcd0ecbc71ea12c81a41fd18f13108c369ccdd6](https://github.com/Liu233w/acm-statistics/tree/adcd0ecbc71ea12c81a41fd18f13108c369ccdd6)
本地测试访问`http://localhost:12001/api/crawlers/vjudge/test001`完全正常，`"error":false`
请问是有可能是因为近期的更新吗

**Comment by Liu233w** [comment]
如果是正常的话，你可以试试在根目录使用 `make up` 来启动项目，然后在浏览器里访问 `localhost:3000` 试一下。（需要安装make 和docker）

**Comment by Hukeqing** [comment]
最近我重新去服务器上看了一下，我发现之前的那个错误突然不出现了……目前是正常运行了，我也不知道发生了什么，我也没管过那个服务器的环境什么的。总之感谢大佬了
