### ISSUE TITLE
添加牛客oj

### ISSUE THREAD

**Issue by bluebear4** [Liu233w/acm-statistics#845]
可不可以加个牛客oj的查询呀

**Comment by Liu233w** [comment]
大佬可以给个链接吗？

**Comment by bluebear4** [comment]
https://ac.nowcoder.com/acm/contest/vip-index




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liu233w"<notifications@github.com&gt;; 
发送时间: 2020年3月14日(星期六) 凌晨0:01
收件人: "Liu233w/acm-statistics"<acm-statistics@noreply.github.com&gt;; 
抄送: "甲基绿和吡罗红"<347278372@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Liu233w/acm-statistics] 建议 (#845)





 
大佬可以给个链接吗？

**Comment by Liu233w** [comment]
`https://ac.nowcoder.com/acm/contest/profile/985979960/practice-coding`

看起来链接的地址是这样的形式。这样的话还需要一个从用户名转换到id的方法

**Comment by Liu233w** [comment]
初步查了一下，可以用 `https://ac.nowcoder.com/acm/contest/status-list?token=&id=1&searchUserName=wwwlsmcom&_=1584170797471` 的形式查看用户信息。其中ID是contest的id。

获取题目列表可以用 `https://ac.nowcoder.com/acm/contest/profile/112946/practice-coding?pageSize=200&search=&statusTypeFilter=5&languageCategoryFilter=-1&orderType=DESC&page=1`

目前还没找到有效地从用户名获取id的方式
