### ISSUE TITLE
爬虫：添加Atcoder

### ISSUE THREAD

**Issue by Meulsama** [Liu233w/acm-statistics#973]
添加Atcoder的做题情况
可以绑定不同的用户ID到同一个账号上比如说QQ。

**Comment by Liu233w** [comment]
域名： atcoder.jp
找到一个API： https://github.com/kenkoooo/AtCoderProblems

查询用户做题情况： https://kenkoooo.com/atcoder/atcoder-api/results?user=wata

p.s. 绑定不同ID的功能已经有了，到时候把爬虫一加就好了

**Comment by Meulsama** [comment]
没注意到绑定不同的ID功能已经有了，十分感谢贵校的网站！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Liu233w"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 晚上10:12
收件人:&nbsp;"Liu233w/acm-statistics"<acm-statistics@noreply.github.com&gt;;
抄送:&nbsp;"1"<1140427013@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Liu233w/acm-statistics] 添加网站 不同用户名的解决方案 (#973)





 
域名： atcoder.jp
 找到一个API： https://github.com/kenkoooo/AtCoderProblems
 
查询用户做题情况： https://kenkoooo.com/atcoder/atcoder-api/results?user=wata
 
p.s. 绑定不同ID的功能已经有了，到时候把爬虫一加就好了

**Comment by Liu233w** [comment]
@all-contributors add @Meulsama for ideas
